modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "ridetogether"
version = "${version}"
displayName = "RideTogether"
authors = "Gallon Emilien"
description = '''
A mod that makes it possible for two players to ride one horse.
'''
logoFile = "ride-together.png"

[[dependencies.ridetogether]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "architectury"
mandatory = true
versionRange = "[10.1.20,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ridetogether.mixins.json"
