plugins {
    id 'com.gradleup.shadow' version '9.2.2'
}

architectury {
    common(rootProject.enabled_platforms.split(','))
}

configurations {
    shadowCommon
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
}
