modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "ridetogether"
version = "${version}"
displayName = "RideTogether"
authors = "Gallon Emilien"
description = '''
A mod that makes it possible for two players to ride one horse.
'''
#logoFile = ""

[[dependencies.ridetogether]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,20.7)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,1.20.7)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "architectury"
type = "required"
versionRange = "[12.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ridetogether.mixins.json"
