modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache-2.0"

[[mods]]
modId = "ridetogether"
version = "${version}"
displayName = "RideTogether"
authors = "Gallon Emilien"
description = '''
A mod that makes it possible for two players to ride one horse.
'''
logoFile = "ride-together.png"

[[dependencies.ridetogether]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ridetogether.mixins.json"
