modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "ridetogether"
version = "${version}"
displayName = "RideTogether"
authors = "Gallon Emilien"
description = '''
A mod that makes it possible for two players to ride one horse.
'''
logoFile = "ride-together.png"

[[dependencies.ridetogether]]
modId = "neoforge"
type = "required"
versionRange = "[21.9.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ridetogether]]
modId = "architectury"
type = "required"
versionRange = "[18.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ridetogether.mixins.json"
